# Develop stage
FROM node:alpine
EXPOSE 8080

WORKDIR '/app/'

COPY ./package*.json /app/

RUN npm install -g @quasar/cli
RUN npm install --save-dev quasar-cli@latest

COPY . /app/

CMD ["quasar", "dev"]
