apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: bomarconi/quasar-client
    context: ./client/
    # Directory containing the artifact's sources
    docker:
      dockerfile: Dockerfile.dev
    # For hot-reloading
    sync:
      'client/src/*': ./client/src/
  - image: bomarconi/formbuilder-server
    context: ./R3NextGenBackend/R3NextGenBackend/
    docker:
      dockerfile: Dockerfile.dev
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s\client-cluster-ip-service.yaml
    - k8s\client-deployment.yaml
    - k8s\database-formbuilder-persistent-volume-claim.yaml
    - k8s\formbuilder-server-cluster-ip-service.yaml
    - k8s\formbuilder-server-deployment.yaml
    - k8s\ingress-service.yaml
