apiVersion: v1
# Kubernetes must find an instance of storage that meets the spec requirements
kind: PersistentVolumeClaim
metadata:
  name: database-formbuilder-persistent-volume-claim
spec:
  accessModes:
    # Can be used by a single node
    - ReadWriteOnce
  resources:
    requests:
      # Kubernetes find a storage that has 1gb of space
      storage: 1Gi